name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm ci
        npm run build --if-present
        npm test
      env:
        CI: true
    - name: Install Semantic Release Tool
      run: |
            npm install --save-dev semantic-release
            npm install --save-dev @semantic-release/commit-analyzer
            npm install --save-dev @semantic-release/git
            npm install --save-dev @semantic-release/release-notes-generator
            npm install --save-dev @semantic-release/github
            npm install --save-dev @semantic-release/changelog
            npm install --save-dev @semantic-release/exec
            npm install --save-dev @semantic-release/npm
    - name: Semantic Release
      run: npx semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_PAT }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: Run a one-line script
      run: echo Semantic release flow completed
